# fly.toml app configuration file generated for hc-demo on 2026-09-22T15:57:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hc-demo'
primary_region = 'iad'

[build]

[env]
  JEV_PROVIDER = 'demo'
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '10s'
    method = 'get'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
