app = "rkendel1-hc-demo"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  JEV_PROVIDER = "demo"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "get"
    path = "/healthz"
